- name: mysql configuration
  hosts: mysql
  become: yes
  tasks:
    - name: install mysql
      ansible.builtin.dnf:
        name: mysql-server -y
        state: present

    - name: start and enable mysql
      ansible.builtin.service:
        name: mysqld
        statr: started
        enabled: yes

    - name: set root password
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1