- name: shipping configuration
  hosts: shipping
  become: yes
  tasks:
    - name: install maven
      ansible.builtin.dnf:
        name: maven 
        state: present

    - name: system user creation
      ansible.builtin.user:
        name: roboshop
        system: true
        home: /app
        shell: /sbin/mologin
        comment: "roboshop system user"

    - name: create directory
      ansible.builtin.file:
        path: /app
        state: directory


    - name: download zip code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
        dest: /tmp/shipping.zip

    - name: download shipping code
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes
    
    - name: install dependencies
      ansible.builtin.command: mvn clean package 
      args:
        chdir: /app

    - name: install dependencies
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
      args:
        chdir: /app

    - name: copy shipping.service
      ansible.builtin.template:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: start and enable shipping
      ansible.builtin.service:
        name: shipping
        state: restarted
        enabled: yes

    - name: install mysql client
      ansible.builtin.dnf:
        name: mysql 
        state: present

    - name: import shipping data
      community.mysql.mysql_db:
        state: import
        name: all
        login_host: "{{ MYSQL_HOST }}"
        login_user: root
        login_password: RoboShop@1
        target: mysql 
        loop:
        - /app/db/schema.sql
        - /app/db/app-user.sql 
        - /app/db/master-data.sql

    - name: start and enable shipping
      ansible.builtin.service:
        name: shipping
        state: restarted
        enabled: yes


    
