- name: user configuration
  hosts: user
  become: yes
  tasks:
    - name: enable nodejs 20
      ansible.builtin.command: dnf enable nodejs:20 -yes

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: system user creation
      ansible.builtin.user:
        system: true 
        home: /app
        shell: /sbin/nologin
        comment: "Roboshop system user"

    - name: create a directory
      ansible.builtin.file:
        path: /app
        state: directory


    - name: download zip code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
        dest: /tmp/user.zip

    - name: unarchive user code
      ansible.builtin.unarchive:
        src: /tmp/user.zip
        dest: /app
        remote_src: yes 

    - name: install dependencies
      community.general.npm:
        path: /app

    - name: copy user service
      ansible.builtin.template:
        src: user.service
        dest: /etc/systemd/system/user.service
        
    - name: start and enable user
      ansible.builtin.service:
        name: user
        state: restarted
        enabled: yes
    


